package ast;

public enum SuggestionTypeEnum {
    IDENTIFIER_ASSIGNMENT,
    VARIABLE_DEFINED_NOT_USED,
    PARAMETER_NOT_USED,
    REDUNDANT_INITIALIZATION,
    WHILE_TO_FOR,
    VARIABLE_CAN_BE_NULL,
    EXCEPTION_SPLIT,
    STRING_CONCATENATION,
    NESTED_IF_TO_SINGLE_IF,
    IF_ELSE_TO_TERNARY,
    FOR_LOOP_TO_FOR_EACH,
    STRING_EQUALITY_COMPARISON,
    SAFE_CAST
}
