package ast;

public enum SuggestionTypeEnum {
    IDENTIFIER_ASSIGNMENT,
    VARIABLE_DEFINED_NOT_USED,
    PARAMETER_NOT_USED,
    REDUNDANT_INITIALIZATION,
    WHILE_TO_FOR,
    VARIABLE_CAN_BE_NULL
}
